# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ntp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ntp.proto',
  package='ntp',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tntp.proto\x12\x03ntp\"\x0c\n\nNtpRequest\"\x1b\n\x08NtpReply\x12\x0f\n\x07message\x18\x01 \x01(\x03\x32\x30\n\x03Ntp\x12)\n\x05Query\x12\x0f.ntp.NtpRequest\x1a\r.ntp.NtpReply\"\x00\x62\x06proto3'
)




_NTPREQUEST = _descriptor.Descriptor(
  name='NtpRequest',
  full_name='ntp.NtpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=30,
)


_NTPREPLY = _descriptor.Descriptor(
  name='NtpReply',
  full_name='ntp.NtpReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ntp.NtpReply.message', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['NtpRequest'] = _NTPREQUEST
DESCRIPTOR.message_types_by_name['NtpReply'] = _NTPREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NtpRequest = _reflection.GeneratedProtocolMessageType('NtpRequest', (_message.Message,), {
  'DESCRIPTOR' : _NTPREQUEST,
  '__module__' : 'ntp_pb2'
  # @@protoc_insertion_point(class_scope:ntp.NtpRequest)
  })
_sym_db.RegisterMessage(NtpRequest)

NtpReply = _reflection.GeneratedProtocolMessageType('NtpReply', (_message.Message,), {
  'DESCRIPTOR' : _NTPREPLY,
  '__module__' : 'ntp_pb2'
  # @@protoc_insertion_point(class_scope:ntp.NtpReply)
  })
_sym_db.RegisterMessage(NtpReply)



_NTP = _descriptor.ServiceDescriptor(
  name='Ntp',
  full_name='ntp.Ntp',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=61,
  serialized_end=109,
  methods=[
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='ntp.Ntp.Query',
    index=0,
    containing_service=None,
    input_type=_NTPREQUEST,
    output_type=_NTPREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NTP)

DESCRIPTOR.services_by_name['Ntp'] = _NTP

# @@protoc_insertion_point(module_scope)
